### ISSUE TITLE
Remove carer question?

### ISSUE THREAD

**Issue by mferrare** [LLAW3301/docassemble-LLAW33012020S1P17#20]
@cata0036 is this question necessary?  If not, I think we should remove it. See also Issue #9

```
# User information
# Starting point for progress bar
progress: 3
question: Welcome to the NDIS Advisor!
fields:
  - What is your full name?: user_fullname  
  - Are you using this app with the presence of a {carer} or support person?: user_carer
    datatype: yesnoradio
under: |
  You do not need to have a carer with you to use this app. 
terms:
  carer: |
    A carer is an individual who provides personal care, support and assistance to other individual who needs it because that individual has a disability, mental condition, mental illness or is frail and aged. (*Carer Recognition Act 2010* (Cth), s5)
---
```
